upvote feature
beingcodr/CodeMod pull request #1
Opened 2020-06-11 16:45 UTC by Aadi-27

Upvote feature

2020-06-11 17:48 UTC, beingcodr requested changes

2020-06-11 17:48 UTC, beingcodr commented on commands/upvote.js
> +      discordId: message.mentions.users.first().id,
Change `message.mentions.users.first().id` to `mentionedUser.id`

2020-06-11 17:48 UTC, beingcodr commented on commands/upvote.js
> +      try {
Change the entire `try catch` to 

```
messageErrorAsync(
    message,
    `<@!${mentionedMember.id}> is not registered in the database`,
    `<@!${message.author.id}>, the user you mentioned is not registered in the DB`
)
```

2020-06-11 17:48 UTC, beingcodr commented on commands/upvote.js
> +    if (!args.length > 1) {
The condition should be `if(args.length === 1)`

2020-06-11 17:48 UTC, beingcodr commented on commands/upvote.js
> +      if (args === "codeError") {
Make theses `if`'s to `switch` case and add a `default` as **Invalid argument**

2020-06-11 17:48 UTC, beingcodr commented on commands/upvote.js
> +      try {
Change the entire `try catch` to

```
messageErrorAsync(
    message,
    `Please upvote for only one type of help at a time.`,
    `<@!${message.author.id}>, please upvote for only one type of help at a time`
)
```

2020-06-11 17:48 UTC, beingcodr commented on commands/upvote.js
> +    Member.update(
Could you refactor this code to **Mongoose** syntax like `member.save()` and all

2020-06-11 17:48 UTC, beingcodr commented on commands/upvote.js
> +    let pointInc = member[points],
Add `args = args.slice(1).join('')` above this code, to get rid of the **@mentioned user** from the **args**

2020-06-11 17:56 UTC, rahul1116 commented
@Aadi-27 You also have to `git pull` this branch to get all the updated code

2020-06-12 09:14 UTC, beingcodr approved these changes

2020-06-12 09:14 UTC, merged